#define BITWIDTH 16
#define LANES 32
#define FIFO_SIZE 512
#define COMPUTE_LATENCY 10
#define RF_MEM_DEPTH 512
#define ACCUM_MEM_DEPTH 64
#define INST_MEM_DEPTH 2048
#define DOT_PRODUCTS LANES
#define DATAW (BITWIDTH * LANES)