#pragma once

#define INSTRUCTION_INTERFACE 0
#define MVU_WRITEBACK_INTERFACE 1
#define VEW_WRITEBACK_INTERFACE 2
#define FEEDFORWARD_INTERFACE 3

#define DEC_INSTRUCTION_INTERFACE_DATAW 256
#define VEW_INSTRUCTION_INTERFACE_DATAW 256
#define VEW_WB0_INTERFACE_DATAW 256
#define VEW_WB1_INTERFACE_DATAW 256
#define VEW_FEEDFORWARD_INTERFACE_DATAW 256
#define MVU_INSTRUCTION_INTERFACE_DATAW 256
#define MVU_FEEDFORWARD_INTERFACE_DATAW 256
#define MVU_WRITEBACK_INTERFACE_DATAW 256